### ISSUE TITLE
There are RT issues

### ISSUE THREAD

**Issue by eserte** [JJ/perl-GitHub-Actions#15]
Please see: https://rt.cpan.org/Ticket/Display.html?id=134116

**Comment by JJ** [comment]
Oh, I hadn't seen them. Thanks a lot!

**Comment by JJ** [comment]
I have checked that, and it should work now; as a matter of fact, only fails in BSD. Do you have an idea of whythis happens?

**Comment by eserte** [comment]
It fails if https://github.com/reneeb/Perl-Critic-OTRS is installed. However, it seems that this module was withdrawn from CPAN, so my newer smokers don't have it installed and do not fail.

**Comment by JJ** [comment]
So I guess this can be closed?

**Comment by eserte** [comment]
Sorry for not answering --- it depends. I did not uninstall Perl-Critic-OTRS from my old smokers, so you will still get fail reports in the future. Maybe best is to make the perlcritic test an author/release-only test.
